name: Pylint, Pytest, Black, and Build

on: [push]

jobs:
  setup:
    runs-on: macos-latest
    strategy:
      matrix:
        os: [macos-latest]
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies (macOS)
      run: |
        brew install gettext zlib bzip2
        brew link --force gettext
        echo "LDFLAGS=-L/usr/local/opt/gettext/lib -L/usr/local/opt/zlib/lib -L/usr/local/opt/bzip2/lib" >> $GITHUB_ENV
        echo "CPPFLAGS=-I/usr/local/opt/gettext/include -I/usr/local/opt/zlib/include -I/usr/local/opt/bzip2/include" >> $GITHUB_ENV
        echo "PKG_CONFIG_PATH=/usr/local/opt/gettext/lib/pkgconfig:/usr/local/opt/zlib/lib/pkgconfig:/usr/local/opt/bzip2/lib/pkgconfig" >> $GITHUB_ENV
        echo "/usr/local/opt/gettext/lib" >> $GITHUB_PATH
        echo "/usr/local/opt/zlib/lib" >> $GITHUB_PATH
        echo "/usr/local/opt/bzip2/lib" >> $GITHUB_PATH
        export DYLD_LIBRARY_PATH=/usr/local/opt/gettext/lib:/usr/local/opt/zlib/lib:/usr/local/opt/bzip2/lib:$DYLD_LIBRARY_PATH
        echo "DYLD_LIBRARY_PATH=/usr/local/opt/gettext/lib:/usr/local/opt/zlib/lib:/usr/local/opt/bzip2/lib:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build pyinstaller
        pip install -r requirements.txt

    - name: Build binary
      run: |
        pyinstaller --onefile --hidden-import=colorama src/ipnet.py

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: ipnet-${{ matrix.os }}-${{ matrix.python-version }}
        path: dist/ipnet*
